spring.application.name=ArquitecturaSpringBoot
server.port=8090
mensaje.bienvenida=Bienvenido

# spring.datasource.url=jdbc:h2:mem:miapp
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update

# H2 Console para ver los datos
# spring.h2.console.enabled=true

# Para los test de containers de Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/curso_testing
spring.datasource.username=scalian
spring.datasource.password=scalian
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.jpa.open-in-view=false

# src/main/resources/application.properties
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration