CREATE SEQUENCE ORDER_HEADER_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE ORDER_HEADER (
    ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    STATUS VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_ORDER_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);