INSERT INTO CUSTOMER (ID, NAME, EMAIL)
VALUES (CUSTOMER_SEQ.NEXTVAL, 'Juan Perez', 'juan@example.com');

INSERT INTO CUSTOMER (ID, NAME, EMAIL)
VALUES (CUSTOMER_SEQ.NEXTVAL, 'Ana Lopez', 'ana@example.com');

INSERT INTO ORDER_HEADER (ID, CUSTOMER_ID, STATUS)
VALUES (ORDER_HEADER_SEQ.NEXTVAL, 1, 'CREATED');

INSERT INTO ORDER_HEADER (ID, CUSTOMER_ID, STATUS)
VALUES (ORDER_HEADER_SEQ.NEXTVAL, 1, 'SHIPPED');

INSERT INTO ORDER_HEADER (ID, CUSTOMER_ID, STATUS)
VALUES (ORDER_HEADER_SEQ.NEXTVAL, 2, 'CREATED');